### ISSUE TITLE
Are you aware of ImgBot?

### ISSUE THREAD

**Issue by TPS** [devedse/WebOptimizationProject#3]
@devedse It looks like you're improving on the concept of https://github.com/dabutvin/Imgbot .  Kudos!

**Comment by devedse** [comment]
I've actually created this from scratch. So I'm wondering if they took my code :) and built upon it

**Comment by TPS** [comment]
I _think_ not, as they seemed unaware of FileOptimizer until [I opened up an RFE](https://github.com/dabutvin/Imgbot/issues/467) quite sometime after their launch.

I suppose this is 1 of those "great minds thinking alike" ideas.

**Comment by TPS** [comment]
Per https://github.com/dabutvin/Imgbot/issues/467#issuecomment-647177717, obviously yes. 🙇🏾‍♂️
